//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class ComSysNotice_Config :  Bright.Config.BeanBase 
{
    public ComSysNotice_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Des = _buf.ReadString();
        Content = _buf.ReadString();
        WaitTime = _buf.ReadInt();
        Par1 = _buf.ReadInt();
        Par2 = _buf.ReadInt();
        PostInit();
    }

    public static ComSysNotice_Config DeserializeComSysNotice_Config(ByteBuf _buf)
    {
        return new Game.ComSysNotice_Config(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 说明
    /// </summary>
    public string Des { get; private set; }
    /// <summary>
    /// 全服公告
    /// </summary>
    public string Content { get; private set; }
    /// <summary>
    /// 延迟播报(秒)
    /// </summary>
    public int WaitTime { get; private set; }
    /// <summary>
    /// 控制参数1
    /// </summary>
    public int Par1 { get; private set; }
    /// <summary>
    /// 控制参数2
    /// </summary>
    public int Par2 { get; private set; }

    public const int __ID__ = 1887079553;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Des:" + Des + ","
        + "Content:" + Content + ","
        + "WaitTime:" + WaitTime + ","
        + "Par1:" + Par1 + ","
        + "Par2:" + Par2 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
