//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game1000_Gear :  Bright.Config.BeanBase 
{
    public Game1000_Gear(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        房间类型 = _buf.ReadInt();
        Gear1 = _buf.ReadInt();
        Gear2 = _buf.ReadInt();
        Gear3 = _buf.ReadInt();
        Gear4 = _buf.ReadInt();
        Gear5 = _buf.ReadInt();
        PostInit();
    }

    public static Game1000_Gear DeserializeGame1000_Gear(ByteBuf _buf)
    {
        return new Game.Game1000_Gear(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int 房间类型 { get; private set; }
    /// <summary>
    /// 挡位1
    /// </summary>
    public int Gear1 { get; private set; }
    /// <summary>
    /// 挡位2
    /// </summary>
    public int Gear2 { get; private set; }
    /// <summary>
    /// 挡位3
    /// </summary>
    public int Gear3 { get; private set; }
    /// <summary>
    /// 挡位
    /// </summary>
    public int Gear4 { get; private set; }
    /// <summary>
    /// 挡位5
    /// </summary>
    public int Gear5 { get; private set; }

    public const int __ID__ = 505123041;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "房间类型:" + 房间类型 + ","
        + "Gear1:" + Gear1 + ","
        + "Gear2:" + Gear2 + ","
        + "Gear3:" + Gear3 + ","
        + "Gear4:" + Gear4 + ","
        + "Gear5:" + Gear5 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
