//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game700_Line_Config :  Bright.Config.BeanBase 
{
    public Game700_Line_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Roulette1 = _buf.ReadInt();
        Roulette2 = _buf.ReadInt();
        Roulette3 = _buf.ReadInt();
        Roulette4 = _buf.ReadInt();
        Roulette5 = _buf.ReadInt();
        PostInit();
    }

    public static Game700_Line_Config DeserializeGame700_Line_Config(ByteBuf _buf)
    {
        return new Game.Game700_Line_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 第一列
    /// </summary>
    public int Roulette1 { get; private set; }
    /// <summary>
    /// 第二列
    /// </summary>
    public int Roulette2 { get; private set; }
    /// <summary>
    /// 第三列
    /// </summary>
    public int Roulette3 { get; private set; }
    /// <summary>
    /// 第四列
    /// </summary>
    public int Roulette4 { get; private set; }
    /// <summary>
    /// 第五列
    /// </summary>
    public int Roulette5 { get; private set; }

    public const int __ID__ = 680387575;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Roulette1:" + Roulette1 + ","
        + "Roulette2:" + Roulette2 + ","
        + "Roulette3:" + Roulette3 + ","
        + "Roulette4:" + Roulette4 + ","
        + "Roulette5:" + Roulette5 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
