//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game800_Base_Config :  Bright.Config.BeanBase 
{
    public Game800_Base_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RoomType = _buf.ReadInt();
        Gear1 = _buf.ReadInt();
        Gear2 = _buf.ReadInt();
        Gear3 = _buf.ReadInt();
        Gear4 = _buf.ReadInt();
        Gear5 = _buf.ReadInt();
        Rate1 = _buf.ReadInt();
        Rate2 = _buf.ReadInt();
        Rate3 = _buf.ReadInt();
        Rate4 = _buf.ReadInt();
        Rate5 = _buf.ReadInt();
        PostInit();
    }

    public static Game800_Base_Config DeserializeGame800_Base_Config(ByteBuf _buf)
    {
        return new Game.Game800_Base_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int RoomType { get; private set; }
    /// <summary>
    /// 挡位1
    /// </summary>
    public int Gear1 { get; private set; }
    /// <summary>
    /// 挡位2
    /// </summary>
    public int Gear2 { get; private set; }
    /// <summary>
    /// 挡位3
    /// </summary>
    public int Gear3 { get; private set; }
    /// <summary>
    /// 挡位4
    /// </summary>
    public int Gear4 { get; private set; }
    /// <summary>
    /// 挡位5
    /// </summary>
    public int Gear5 { get; private set; }
    /// <summary>
    /// 赔率1
    /// </summary>
    public int Rate1 { get; private set; }
    /// <summary>
    /// 赔率2
    /// </summary>
    public int Rate2 { get; private set; }
    /// <summary>
    /// 赔率3
    /// </summary>
    public int Rate3 { get; private set; }
    /// <summary>
    /// 赔率4
    /// </summary>
    public int Rate4 { get; private set; }
    /// <summary>
    /// 赔率5
    /// </summary>
    public int Rate5 { get; private set; }

    public const int __ID__ = -192613189;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "RoomType:" + RoomType + ","
        + "Gear1:" + Gear1 + ","
        + "Gear2:" + Gear2 + ","
        + "Gear3:" + Gear3 + ","
        + "Gear4:" + Gear4 + ","
        + "Gear5:" + Gear5 + ","
        + "Rate1:" + Rate1 + ","
        + "Rate2:" + Rate2 + ","
        + "Rate3:" + Rate3 + ","
        + "Rate4:" + Rate4 + ","
        + "Rate5:" + Rate5 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
