//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Share_PromoteUsers_Config :  Bright.Config.BeanBase 
{
    public Share_PromoteUsers_Config(ByteBuf _buf) 
    {
        PromoteUsers = _buf.ReadInt();
        PromoteUsersReward = _buf.ReadFloat();
        LightImage = _buf.ReadString();
        DrakImage = _buf.ReadString();
        PostInit();
    }

    public static Share_PromoteUsers_Config DeserializeShare_PromoteUsers_Config(ByteBuf _buf)
    {
        return new Game.Share_PromoteUsers_Config(_buf);
    }

    /// <summary>
    /// 推广用户
    /// </summary>
    public int PromoteUsers { get; private set; }
    /// <summary>
    /// 推广用户奖励
    /// </summary>
    public float PromoteUsersReward { get; private set; }
    /// <summary>
    /// 金币图片(亮)
    /// </summary>
    public string LightImage { get; private set; }
    /// <summary>
    /// 金币图片(暗)
    /// </summary>
    public string DrakImage { get; private set; }

    public const int __ID__ = 1475298781;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PromoteUsers:" + PromoteUsers + ","
        + "PromoteUsersReward:" + PromoteUsersReward + ","
        + "LightImage:" + LightImage + ","
        + "DrakImage:" + DrakImage + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
