//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Share_PayUsers_Config :  Bright.Config.BeanBase 
{
    public Share_PayUsers_Config(ByteBuf _buf) 
    {
        PayUsers = _buf.ReadInt();
        PayUsersReward = _buf.ReadInt();
        LightImage = _buf.ReadString();
        DrakImage = _buf.ReadString();
        PostInit();
    }

    public static Share_PayUsers_Config DeserializeShare_PayUsers_Config(ByteBuf _buf)
    {
        return new Game.Share_PayUsers_Config(_buf);
    }

    /// <summary>
    /// 付费用户
    /// </summary>
    public int PayUsers { get; private set; }
    /// <summary>
    /// 付费用户奖励
    /// </summary>
    public int PayUsersReward { get; private set; }
    /// <summary>
    /// 金币图片(亮)
    /// </summary>
    public string LightImage { get; private set; }
    /// <summary>
    /// 金币图片(暗)
    /// </summary>
    public string DrakImage { get; private set; }

    public const int __ID__ = -2016940859;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PayUsers:" + PayUsers + ","
        + "PayUsersReward:" + PayUsersReward + ","
        + "LightImage:" + LightImage + ","
        + "DrakImage:" + DrakImage + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
