//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Sounds_Config :  Bright.Config.BeanBase 
{
    public Sounds_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AudioType = _buf.ReadInt();
        TriggerRatio = _buf.ReadFloat();
        FileName = _buf.ReadString();
        PostInit();
    }

    public static Sounds_Config DeserializeSounds_Config(ByteBuf _buf)
    {
        return new Game.Sounds_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 音效类型
    /// </summary>
    public int AudioType { get; private set; }
    /// <summary>
    /// 音量
    /// </summary>
    public float TriggerRatio { get; private set; }
    /// <summary>
    /// 地址
    /// </summary>
    public string FileName { get; private set; }

    public const int __ID__ = -2031713855;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AudioType:" + AudioType + ","
        + "TriggerRatio:" + TriggerRatio + ","
        + "FileName:" + FileName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
