//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class SubPackConfig :  Bright.Config.BeanBase 
{
    public SubPackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BtnName = _buf.ReadString();
        GameName = _buf.ReadString();
        Roomid = _buf.ReadInt();
        PostInit();
    }

    public static SubPackConfig DeserializeSubPackConfig(ByteBuf _buf)
    {
        return new Game.SubPackConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 分包名
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 按钮名
    /// </summary>
    public string BtnName { get; private set; }
    /// <summary>
    /// 游戏名
    /// </summary>
    public string GameName { get; private set; }
    /// <summary>
    /// 游戏id
    /// </summary>
    public int Roomid { get; private set; }

    public const int __ID__ = 1197901855;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BtnName:" + BtnName + ","
        + "GameName:" + GameName + ","
        + "Roomid:" + Roomid + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
