//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Game
{
   
public partial class TbFortyTwoGrid_Config
{
    private readonly Dictionary<int, Game.FortyTwoGrid_Config> _dataMap;
    private readonly List<Game.FortyTwoGrid_Config> _dataList;
    
    public TbFortyTwoGrid_Config(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Game.FortyTwoGrid_Config>();
        _dataList = new List<Game.FortyTwoGrid_Config>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Game.FortyTwoGrid_Config _v;
            _v = Game.FortyTwoGrid_Config.DeserializeFortyTwoGrid_Config(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Game.FortyTwoGrid_Config> DataMap => _dataMap;
    public List<Game.FortyTwoGrid_Config> DataList => _dataList;

    public Game.FortyTwoGrid_Config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Game.FortyTwoGrid_Config Get(int key) => _dataMap[key];
    public Game.FortyTwoGrid_Config this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}