//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Game
{
   
public partial class TbGameItemConfig
{
    private readonly Dictionary<string, Game.GameItemConfig> _dataMap;
    private readonly List<Game.GameItemConfig> _dataList;
    
    public TbGameItemConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, Game.GameItemConfig>();
        _dataList = new List<Game.GameItemConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Game.GameItemConfig _v;
            _v = Game.GameItemConfig.DeserializeGameItemConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<string, Game.GameItemConfig> DataMap => _dataMap;
    public List<Game.GameItemConfig> DataList => _dataList;

    public Game.GameItemConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Game.GameItemConfig Get(string key) => _dataMap[key];
    public Game.GameItemConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}