//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Game
{
   
public partial class TbGame1000_AwardLine
{
    private readonly Dictionary<int, Game.Game1000_AwardLine> _dataMap;
    private readonly List<Game.Game1000_AwardLine> _dataList;
    
    public TbGame1000_AwardLine(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Game.Game1000_AwardLine>();
        _dataList = new List<Game.Game1000_AwardLine>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Game.Game1000_AwardLine _v;
            _v = Game.Game1000_AwardLine.DeserializeGame1000_AwardLine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Game.Game1000_AwardLine> DataMap => _dataMap;
    public List<Game.Game1000_AwardLine> DataList => _dataList;

    public Game.Game1000_AwardLine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Game.Game1000_AwardLine Get(int key) => _dataMap[key];
    public Game.Game1000_AwardLine this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}