//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class UIPanel_Config :  Bright.Config.BeanBase 
{
    public UIPanel_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PanelName = _buf.ReadString();
        Type = _buf.ReadInt();
        Fullview = _buf.ReadBool();
        Ignoreguide = _buf.ReadBool();
        Cache = _buf.ReadBool();
        Preload = _buf.ReadBool();
        PrefabPath = _buf.ReadString();
        SubTypeLayer = _buf.ReadInt();
        EnumLayerType = _buf.ReadInt();
        AnimationType = _buf.ReadInt();
        PostInit();
    }

    public static UIPanel_Config DeserializeUIPanel_Config(ByteBuf _buf)
    {
        return new Game.UIPanel_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// UI名
    /// </summary>
    public string PanelName { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 全屏显示
    /// </summary>
    public bool Fullview { get; private set; }
    /// <summary>
    /// 是否忽略引导
    /// </summary>
    public bool Ignoreguide { get; private set; }
    /// <summary>
    /// 是否缓存
    /// </summary>
    public bool Cache { get; private set; }
    /// <summary>
    /// 是否预加载
    /// </summary>
    public bool Preload { get; private set; }
    /// <summary>
    /// prefab路径
    /// </summary>
    public string PrefabPath { get; private set; }
    /// <summary>
    /// 子层级
    /// </summary>
    public int SubTypeLayer { get; private set; }
    /// <summary>
    /// 分类层级
    /// </summary>
    public int EnumLayerType { get; private set; }
    /// <summary>
    /// 动画类型 0,无动画 ,1 非全屏缩放动画
    /// </summary>
    public int AnimationType { get; private set; }

    public const int __ID__ = 966977549;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PanelName:" + PanelName + ","
        + "Type:" + Type + ","
        + "Fullview:" + Fullview + ","
        + "Ignoreguide:" + Ignoreguide + ","
        + "Cache:" + Cache + ","
        + "Preload:" + Preload + ","
        + "PrefabPath:" + PrefabPath + ","
        + "SubTypeLayer:" + SubTypeLayer + ","
        + "EnumLayerType:" + EnumLayerType + ","
        + "AnimationType:" + AnimationType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
