//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg
{
   
public partial class CashOut_Limit_Config
{
    private readonly Dictionary<int, CashOutConfig> _dataMap;
    private readonly List<CashOutConfig> _dataList;
    
    public CashOut_Limit_Config(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, CashOutConfig>();
        _dataList = new List<CashOutConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CashOutConfig _v;
            _v = CashOutConfig.DeserializeCashOutConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, CashOutConfig> DataMap => _dataMap;
    public List<CashOutConfig> DataList => _dataList;

    public CashOutConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CashOutConfig Get(int key) => _dataMap[key];
    public CashOutConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}