using TMPro;
using DragonBones;
using UnityEngine;
using UnityEngine.UI;

namespace HotUpdate
{
	public partial class Top1600Panel
	{
		private Image m_Img_LeftLight;
		private Image m_Img_RightLight;
		private Button m_Btn_Leave;
		private Image m_Img_Head;
		private TextMeshProUGUI m_TxtM_ID;
		private TextMeshProUGUI m_TxtM_Money;
		private Button m_Btn_Rank1;
		private Button m_Btn_Help;
		private RectTransform m_Trans_Target;
		private Button m_Btn_Rank;
		private Button m_Btn_Tour;
		private Button m_Btn_TourRank;
		private RectTransform m_Trans_Effect;
		private RectTransform m_Trans_TextGold0;
		private RectTransform m_Trans_TextGold1;
		private RectTransform m_Trans_TextGold2;
		private RectTransform m_Trans_TextGold3;
		private RectTransform m_Trans_TextGold4;
		private RectTransform m_Trans_TextGold5;
		private RectTransform m_Trans_TextGold6;
		private RectTransform m_Trans_TextGold7;
		private RectTransform m_Trans_TextGold8;
		private RectTransform m_Trans_TextGold9;
		private RectTransform m_Trans_GameTips;
		private RectTransform m_Trans_BigAwardEffect;
		private UnityArmatureComponent m_Dragon_GetGoldEffect;
		private RectTransform m_Trans_WinGoldBg;
		private RectTransform m_Trans_RedGoldBg;
		private RectTransform m_Trans_GreenGoldBg;
		private RectTransform m_Trans_PinkGoldBg;
		private UnityArmatureComponent m_Dragon_AddGoldEffect;
		private RectTransform m_Trans_AddGoldEffect2;
		private RectTransform m_Trans_Respins;
		private RectTransform m_Trans_WinUpTo2500;
		private RectTransform m_Trans_Multiplier ;
		private RectTransform m_Trans_Win;
		private TextMeshProUGUI m_TxtM_WinGold;
		private Text m_Txt_WinGold;
		private RectTransform m_Trans_FortuneTigerFeature;
		private RectTransform m_Trans_Wild;
		private Image m_Img_Icon;
		private Image m_Img_Wild;
		private Toggle m_Tog_Turbo;
		private Button m_Btn_Min;
		private UnityArmatureComponent m_Dragon_Begin;
		private Button m_Btn_BeginSpin;
		private RectTransform m_Trans_Rorate;
		private RectTransform m_Trans_Normal;
		private RectTransform m_Trans_Grey;
		private Button m_Btn_Add;
		private Button m_Btn_Auto;
		private Button m_Btn_Menue;
		private RectTransform m_Trans_GoAutoSpinNum;
		private Text m_Txt_AutoSpinNum;
		private Button m_Btn_CloseAutoSpin;
		private RectTransform m_Trans_Free;
		private RectTransform m_Trans_Content;
		private Text m_Txt_FreeTimes;
		private RectTransform m_Trans_0;
		private RectTransform m_Trans_Not0;
		private Text m_Txt_Gold;
		private Button m_Btn_AddGold;
		private Text m_Txt_SingleGold;
		private Button m_Btn_Bet;
		private Text m_Txt_Score;
		private Button m_Btn_Win;
		private RectTransform m_Trans_Free2;
		private UnityArmatureComponent m_Dragon_Rabbit1;
		private UnityArmatureComponent m_Dragon_Rabbit2;
		private UnityArmatureComponent m_Dragon_Rabbit3;
		private RectTransform m_Trans_GetFreeAni;
		private Image m_Img_Rabbit;
		private RectTransform m_Trans_FreeCount;
		private RectTransform m_Trans_FreeRabbit;
		private RectTransform m_Trans_MenuePanel;
		private Button m_Btn_PayTable;
		private Button m_Btn_Rule;
		private Button m_Btn_CloseMenue;
		private Text m_Txt_Rate10;
		private RectTransform m_Trans_SpecialElement;

		private void GetBindComponents(GameObject go)
		{
			ComponentAutoBindTool autoBindTool = go.GetComponent<ComponentAutoBindTool>();

			m_Img_LeftLight = autoBindTool.GetBindComponent<Image>(0);
			m_Img_RightLight = autoBindTool.GetBindComponent<Image>(1);
			m_Btn_Leave = autoBindTool.GetBindComponent<Button>(2);
			m_Img_Head = autoBindTool.GetBindComponent<Image>(3);
			m_TxtM_ID = autoBindTool.GetBindComponent<TextMeshProUGUI>(4);
			m_TxtM_Money = autoBindTool.GetBindComponent<TextMeshProUGUI>(5);
			m_Btn_Rank1 = autoBindTool.GetBindComponent<Button>(6);
			m_Btn_Help = autoBindTool.GetBindComponent<Button>(7);
			m_Trans_Target = autoBindTool.GetBindComponent<RectTransform>(8);
			m_Btn_Rank = autoBindTool.GetBindComponent<Button>(9);
			m_Btn_Tour = autoBindTool.GetBindComponent<Button>(10);
			m_Btn_TourRank = autoBindTool.GetBindComponent<Button>(11);
			m_Trans_Effect = autoBindTool.GetBindComponent<RectTransform>(12);
			m_Trans_TextGold0 = autoBindTool.GetBindComponent<RectTransform>(13);
			m_Trans_TextGold1 = autoBindTool.GetBindComponent<RectTransform>(14);
			m_Trans_TextGold2 = autoBindTool.GetBindComponent<RectTransform>(15);
			m_Trans_TextGold3 = autoBindTool.GetBindComponent<RectTransform>(16);
			m_Trans_TextGold4 = autoBindTool.GetBindComponent<RectTransform>(17);
			m_Trans_TextGold5 = autoBindTool.GetBindComponent<RectTransform>(18);
			m_Trans_TextGold6 = autoBindTool.GetBindComponent<RectTransform>(19);
			m_Trans_TextGold7 = autoBindTool.GetBindComponent<RectTransform>(20);
			m_Trans_TextGold8 = autoBindTool.GetBindComponent<RectTransform>(21);
			m_Trans_TextGold9 = autoBindTool.GetBindComponent<RectTransform>(22);
			m_Trans_GameTips = autoBindTool.GetBindComponent<RectTransform>(23);
			m_Trans_BigAwardEffect = autoBindTool.GetBindComponent<RectTransform>(24);
			m_Dragon_GetGoldEffect = autoBindTool.GetBindComponent<UnityArmatureComponent>(25);
			m_Trans_WinGoldBg = autoBindTool.GetBindComponent<RectTransform>(26);
			m_Trans_RedGoldBg = autoBindTool.GetBindComponent<RectTransform>(27);
			m_Trans_GreenGoldBg = autoBindTool.GetBindComponent<RectTransform>(28);
			m_Trans_PinkGoldBg = autoBindTool.GetBindComponent<RectTransform>(29);
			m_Dragon_AddGoldEffect = autoBindTool.GetBindComponent<UnityArmatureComponent>(30);
			m_Trans_AddGoldEffect2 = autoBindTool.GetBindComponent<RectTransform>(31);
			m_Trans_Respins = autoBindTool.GetBindComponent<RectTransform>(32);
			m_Trans_WinUpTo2500 = autoBindTool.GetBindComponent<RectTransform>(33);
			m_Trans_Multiplier  = autoBindTool.GetBindComponent<RectTransform>(34);
			m_Trans_Win = autoBindTool.GetBindComponent<RectTransform>(35);
			m_TxtM_WinGold = autoBindTool.GetBindComponent<TextMeshProUGUI>(36);
			m_Txt_WinGold = autoBindTool.GetBindComponent<Text>(37);
			m_Trans_FortuneTigerFeature = autoBindTool.GetBindComponent<RectTransform>(38);
			m_Trans_Wild = autoBindTool.GetBindComponent<RectTransform>(39);
			m_Img_Icon = autoBindTool.GetBindComponent<Image>(40);
			m_Img_Wild = autoBindTool.GetBindComponent<Image>(41);
			m_Tog_Turbo = autoBindTool.GetBindComponent<Toggle>(42);
			m_Btn_Min = autoBindTool.GetBindComponent<Button>(43);
			m_Dragon_Begin = autoBindTool.GetBindComponent<UnityArmatureComponent>(44);
			m_Btn_BeginSpin = autoBindTool.GetBindComponent<Button>(45);
			m_Trans_Rorate = autoBindTool.GetBindComponent<RectTransform>(46);
			m_Trans_Normal = autoBindTool.GetBindComponent<RectTransform>(47);
			m_Trans_Grey = autoBindTool.GetBindComponent<RectTransform>(48);
			m_Btn_Add = autoBindTool.GetBindComponent<Button>(49);
			m_Btn_Auto = autoBindTool.GetBindComponent<Button>(50);
			m_Btn_Menue = autoBindTool.GetBindComponent<Button>(51);
			m_Trans_GoAutoSpinNum = autoBindTool.GetBindComponent<RectTransform>(52);
			m_Txt_AutoSpinNum = autoBindTool.GetBindComponent<Text>(53);
			m_Btn_CloseAutoSpin = autoBindTool.GetBindComponent<Button>(54);
			m_Trans_Free = autoBindTool.GetBindComponent<RectTransform>(55);
			m_Trans_Content = autoBindTool.GetBindComponent<RectTransform>(56);
			m_Txt_FreeTimes = autoBindTool.GetBindComponent<Text>(57);
			m_Trans_0 = autoBindTool.GetBindComponent<RectTransform>(58);
			m_Trans_Not0 = autoBindTool.GetBindComponent<RectTransform>(59);
			m_Txt_Gold = autoBindTool.GetBindComponent<Text>(60);
			m_Btn_AddGold = autoBindTool.GetBindComponent<Button>(61);
			m_Txt_SingleGold = autoBindTool.GetBindComponent<Text>(62);
			m_Btn_Bet = autoBindTool.GetBindComponent<Button>(63);
			m_Txt_Score = autoBindTool.GetBindComponent<Text>(64);
			m_Btn_Win = autoBindTool.GetBindComponent<Button>(65);
			m_Trans_Free2 = autoBindTool.GetBindComponent<RectTransform>(66);
			m_Dragon_Rabbit1 = autoBindTool.GetBindComponent<UnityArmatureComponent>(67);
			m_Dragon_Rabbit2 = autoBindTool.GetBindComponent<UnityArmatureComponent>(68);
			m_Dragon_Rabbit3 = autoBindTool.GetBindComponent<UnityArmatureComponent>(69);
			m_Trans_GetFreeAni = autoBindTool.GetBindComponent<RectTransform>(70);
			m_Img_Rabbit = autoBindTool.GetBindComponent<Image>(71);
			m_Trans_FreeCount = autoBindTool.GetBindComponent<RectTransform>(72);
			m_Trans_FreeRabbit = autoBindTool.GetBindComponent<RectTransform>(73);
			m_Trans_MenuePanel = autoBindTool.GetBindComponent<RectTransform>(74);
			m_Btn_PayTable = autoBindTool.GetBindComponent<Button>(75);
			m_Btn_Rule = autoBindTool.GetBindComponent<Button>(76);
			m_Btn_CloseMenue = autoBindTool.GetBindComponent<Button>(77);
			m_Txt_Rate10 = autoBindTool.GetBindComponent<Text>(78);
			m_Trans_SpecialElement = autoBindTool.GetBindComponent<RectTransform>(79);
		}
	}
}
