using TMPro;
using DragonBones;
using UnityEngine;
using UnityEngine.UI;

namespace HotUpdate
{
	public partial class Top1200Panel
	{
		private Button m_Btn_Leave;
		private Image m_Img_Head;
		private TextMeshProUGUI m_TxtM_ID;
		private TextMeshProUGUI m_TxtM_Money;
		private Button m_Btn_Rank;
		private Button m_Btn_Help;
		private RectTransform m_Trans_Target;
		private RectTransform m_Trans_Mask;
		private RectTransform m_Trans_Effect;
		private RectTransform m_Trans_Lines;
		private RectTransform m_Trans_ElementEffect;
		private RectTransform m_Trans_TextGold4;
		private RectTransform m_Trans_TextGold3;
		private RectTransform m_Trans_TextGold2;
		private RectTransform m_Trans_TextGold1;
		private RectTransform m_Trans_TextGold0;
		private RectTransform m_Trans_GameTips;
		private RectTransform m_Trans_BigAwardEffect;
		private UnityArmatureComponent m_Dragon_ClickBtn;
		private UnityArmatureComponent m_Dragon_ClickBtn2;
		private RectTransform m_Trans_WinGoldBg;
		private RectTransform m_Trans_RedGoldBg;
		private RectTransform m_Trans_GreenGoldBg;
		private RectTransform m_Trans_PinkGoldBg;
		private UnityArmatureComponent m_Dragon_GetGoldEffect;
		private RectTransform m_Trans_Respins;
		private RectTransform m_Trans_WinUpTo2500;
		private RectTransform m_Trans_Multiplier ;
		private RectTransform m_Trans_Win;
		private TextMeshProUGUI m_TxtM_WinGold;
		private Text m_Txt_WinGold;
		private RectTransform m_Trans_FortuneTigerFeature;
		private RectTransform m_Trans_Wild;
		private Image m_Img_Icon;
		private Image m_Img_Wild;
		private TextMeshProUGUI m_TxtM_Gold;
		private Button m_Btn_AddGold;
		private TextMeshProUGUI m_TxtM_SingleGold;
		private Button m_Btn_Bet;
		private TextMeshProUGUI m_TxtM_Score;
		private Button m_Btn_Win;
		private Toggle m_Tog_Turbo;
		private Button m_Btn_Turbo;
		private Button m_Btn_Min;
		private Button m_Btn_BeginSpin;
		private RectTransform m_Trans_Rorate;
		private RectTransform m_Trans_Normal;
		private RectTransform m_Trans_Grey;
		private Button m_Btn_Add;
		private Toggle m_Tog_Auto;
		private Button m_Btn_Auto;
		private Button m_Btn_Menue;
		private RectTransform m_Trans_GoAutoSpinNum;
		private Text m_Txt_AutoSpinNum;
		private Button m_Btn_CloseAutoSpin;
		private RectTransform m_Trans_MenuePanel;
		private Button m_Btn_PayTable;
		private Button m_Btn_Rule;
		private Button m_Btn_CloseMenue;
		private Text m_Txt_Rate10;
		private UnityArmatureComponent m_Dragon_RedPapger;
		private RectTransform m_Trans_SpecialElement;

		private void GetBindComponents(GameObject go)
		{
			ComponentAutoBindTool autoBindTool = go.GetComponent<ComponentAutoBindTool>();

			m_Btn_Leave = autoBindTool.GetBindComponent<Button>(0);
			m_Img_Head = autoBindTool.GetBindComponent<Image>(1);
			m_TxtM_ID = autoBindTool.GetBindComponent<TextMeshProUGUI>(2);
			m_TxtM_Money = autoBindTool.GetBindComponent<TextMeshProUGUI>(3);
			m_Btn_Rank = autoBindTool.GetBindComponent<Button>(4);
			m_Btn_Help = autoBindTool.GetBindComponent<Button>(5);
			m_Trans_Target = autoBindTool.GetBindComponent<RectTransform>(6);
			m_Trans_Mask = autoBindTool.GetBindComponent<RectTransform>(7);
			m_Trans_Effect = autoBindTool.GetBindComponent<RectTransform>(8);
			m_Trans_Lines = autoBindTool.GetBindComponent<RectTransform>(9);
			m_Trans_ElementEffect = autoBindTool.GetBindComponent<RectTransform>(10);
			m_Trans_TextGold4 = autoBindTool.GetBindComponent<RectTransform>(11);
			m_Trans_TextGold3 = autoBindTool.GetBindComponent<RectTransform>(12);
			m_Trans_TextGold2 = autoBindTool.GetBindComponent<RectTransform>(13);
			m_Trans_TextGold1 = autoBindTool.GetBindComponent<RectTransform>(14);
			m_Trans_TextGold0 = autoBindTool.GetBindComponent<RectTransform>(15);
			m_Trans_GameTips = autoBindTool.GetBindComponent<RectTransform>(16);
			m_Trans_BigAwardEffect = autoBindTool.GetBindComponent<RectTransform>(17);
			m_Dragon_ClickBtn = autoBindTool.GetBindComponent<UnityArmatureComponent>(18);
			m_Dragon_ClickBtn2 = autoBindTool.GetBindComponent<UnityArmatureComponent>(19);
			m_Trans_WinGoldBg = autoBindTool.GetBindComponent<RectTransform>(20);
			m_Trans_RedGoldBg = autoBindTool.GetBindComponent<RectTransform>(21);
			m_Trans_GreenGoldBg = autoBindTool.GetBindComponent<RectTransform>(22);
			m_Trans_PinkGoldBg = autoBindTool.GetBindComponent<RectTransform>(23);
			m_Dragon_GetGoldEffect = autoBindTool.GetBindComponent<UnityArmatureComponent>(24);
			m_Trans_Respins = autoBindTool.GetBindComponent<RectTransform>(25);
			m_Trans_WinUpTo2500 = autoBindTool.GetBindComponent<RectTransform>(26);
			m_Trans_Multiplier  = autoBindTool.GetBindComponent<RectTransform>(27);
			m_Trans_Win = autoBindTool.GetBindComponent<RectTransform>(28);
			m_TxtM_WinGold = autoBindTool.GetBindComponent<TextMeshProUGUI>(29);
			m_Txt_WinGold = autoBindTool.GetBindComponent<Text>(30);
			m_Trans_FortuneTigerFeature = autoBindTool.GetBindComponent<RectTransform>(31);
			m_Trans_Wild = autoBindTool.GetBindComponent<RectTransform>(32);
			m_Img_Icon = autoBindTool.GetBindComponent<Image>(33);
			m_Img_Wild = autoBindTool.GetBindComponent<Image>(34);
			m_TxtM_Gold = autoBindTool.GetBindComponent<TextMeshProUGUI>(35);
			m_Btn_AddGold = autoBindTool.GetBindComponent<Button>(36);
			m_TxtM_SingleGold = autoBindTool.GetBindComponent<TextMeshProUGUI>(37);
			m_Btn_Bet = autoBindTool.GetBindComponent<Button>(38);
			m_TxtM_Score = autoBindTool.GetBindComponent<TextMeshProUGUI>(39);
			m_Btn_Win = autoBindTool.GetBindComponent<Button>(40);
			m_Tog_Turbo = autoBindTool.GetBindComponent<Toggle>(41);
			m_Btn_Turbo = autoBindTool.GetBindComponent<Button>(42);
			m_Btn_Min = autoBindTool.GetBindComponent<Button>(43);
			m_Btn_BeginSpin = autoBindTool.GetBindComponent<Button>(44);
			m_Trans_Rorate = autoBindTool.GetBindComponent<RectTransform>(45);
			m_Trans_Normal = autoBindTool.GetBindComponent<RectTransform>(46);
			m_Trans_Grey = autoBindTool.GetBindComponent<RectTransform>(47);
			m_Btn_Add = autoBindTool.GetBindComponent<Button>(48);
			m_Tog_Auto = autoBindTool.GetBindComponent<Toggle>(49);
			m_Btn_Auto = autoBindTool.GetBindComponent<Button>(50);
			m_Btn_Menue = autoBindTool.GetBindComponent<Button>(51);
			m_Trans_GoAutoSpinNum = autoBindTool.GetBindComponent<RectTransform>(52);
			m_Txt_AutoSpinNum = autoBindTool.GetBindComponent<Text>(53);
			m_Btn_CloseAutoSpin = autoBindTool.GetBindComponent<Button>(54);
			m_Trans_MenuePanel = autoBindTool.GetBindComponent<RectTransform>(55);
			m_Btn_PayTable = autoBindTool.GetBindComponent<Button>(56);
			m_Btn_Rule = autoBindTool.GetBindComponent<Button>(57);
			m_Btn_CloseMenue = autoBindTool.GetBindComponent<Button>(58);
			m_Txt_Rate10 = autoBindTool.GetBindComponent<Text>(59);
			m_Dragon_RedPapger = autoBindTool.GetBindComponent<UnityArmatureComponent>(60);
			m_Trans_SpecialElement = autoBindTool.GetBindComponent<RectTransform>(61);
		}
	}
}
