//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public sealed partial class CashOutConfig :  Bright.Config.BeanBase 
{
    public CashOutConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        NextLv = _buf.ReadInt();
        CashoutMax = _buf.ReadInt();
        PostInit();
    }

    public static CashOutConfig DeserializeCashOutConfig(ByteBuf _buf)
    {
        return new CashOutConfig(_buf);
    }

    /// <summary>
    /// 排行区间
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// VIP等级
    /// </summary>
    public int NextLv { get; private set; }
    /// <summary>
    /// 每日兑出限额(分)
    /// </summary>
    public int CashoutMax { get; private set; }

    public const int __ID__ = 590064157;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NextLv:" + NextLv + ","
        + "CashoutMax:" + CashoutMax + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
