//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Threading.Tasks;


namespace cfg
{
   
public sealed class Tables
{
    public Game.TbUIPanel_Config TbUIPanel_Config {get; private set; }
    public Game.TbMailPanel_Config TbMailPanel_Config {get; private set; }
    public Game.TbZeus_Config TbZeus_Config {get; private set; }
    public Game.TbGame500_Gear TbGame500_Gear {get; private set; }
    public Game.TbGame500_Line_Config TbGame500_Line_Config {get; private set; }
    public Game.TbGame600_Gear TbGame600_Gear {get; private set; }
    public Game.TbGame600_JackPot TbGame600_JackPot {get; private set; }
    public Game.TbGame600_Line_Config TbGame600_Line_Config {get; private set; }
    public Game.TbGame700_Base_Config TbGame700_Base_Config {get; private set; }
    public Game.TbGame700_Line_Config TbGame700_Line_Config {get; private set; }
    public Game.TbHead_Config TbHead_Config {get; private set; }
    public Game.TbSounds_Config TbSounds_Config {get; private set; }
    public Game.TbGame800_Base_Config TbGame800_Base_Config {get; private set; }
    public Game.TbGame800_Line_Config TbGame800_Line_Config {get; private set; }
    public Game.TbGameTask TbGameTask {get; private set; }
    public Game.TbSevenDay_Login_Config TbSevenDay_Login_Config {get; private set; }
    public Game.TbShop_Config TbShop_Config {get; private set; }
    public Game.TbConst_Config TbConst_Config {get; private set; }
    public Game.TbVip_lvl_Config TbVip_lvl_Config {get; private set; }
    public Game.TbGameRoomConfig TbGameRoomConfig {get; private set; }
    public Game.TbComSysNotice_Config TbComSysNotice_Config {get; private set; }
    public Game.TbGame601_Gear TbGame601_Gear {get; private set; }
    public Game.TbGame601_JackPot TbGame601_JackPot {get; private set; }
    public Game.TbGame601_Line_Config TbGame601_Line_Config {get; private set; }
    public Game.TbSubPackConfig TbSubPackConfig {get; private set; }
    public CashOut_Limit_Config CashOut_Limit_Config {get; private set; }
    public Game.TbGameItemConfig TbGameItemConfig {get; private set; }
    public Game.TbGame900_Gear TbGame900_Gear {get; private set; }
    public Game.TbGame900_Line_Config TbGame900_Line_Config {get; private set; }
    public Game.TbGame1000_Gear TbGame1000_Gear {get; private set; }
    public Game.TbGame1000_Line_Config TbGame1000_Line_Config {get; private set; }
    public Game.TbGame1100_Gear TbGame1100_Gear {get; private set; }
    public Game.TbGame1100_Line_Config TbGame1100_Line_Config {get; private set; }
    public Game.TbGameMines_Config TbGameMines_Config {get; private set; }
    public Game.TbGame1200_Gear TbGame1200_Gear {get; private set; }
    public Game.TbGame1200_Line_Config TbGame1200_Line_Config {get; private set; }
    public Game.TbGame1300_Gear TbGame1300_Gear {get; private set; }
    public Game.TbGame1400_BetChips TbGame1400_BetChips {get; private set; }
    public Game.TbGame200_Config TbGame200_Config {get; private set; }
    public Game.TbShare_PayUsers_Config TbShare_PayUsers_Config {get; private set; }
    public Game.TbShare_PromoteUsers_Config TbShare_PromoteUsers_Config {get; private set; }
    public Game.TbGame1500_Gear TbGame1500_Gear {get; private set; }
    public Game.TbGame1500_Line_Config TbGame1500_Line_Config {get; private set; }
    public Game.TbGame1000_AwardLine TbGame1000_AwardLine {get; private set; }
    public Game.TbConstLevelParamVIP TbConstLevelParamVIP {get; private set; }
    public Game.TbGame1600_Gear TbGame1600_Gear {get; private set; }
    public Game.TbGame1600_Line_Config TbGame1600_Line_Config {get; private set; }
    public Game.TbHappyGrid_Config TbHappyGrid_Config {get; private set; }
    public Game.TbGameArena TbGameArena {get; private set; }
    public Game.TbGameRank TbGameRank {get; private set; }
    public Game.TbGame602_Gear TbGame602_Gear {get; private set; }
    public Game.TbGame602_JackPot TbGame602_JackPot {get; private set; }
    public Game.TbGame602_Line_Config TbGame602_Line_Config {get; private set; }
    public Game.TbFortyTwoGrid_Config TbFortyTwoGrid_Config {get; private set; }
    public Game.TbGame700_JackPot TbGame700_JackPot {get; private set; }
    public Game.TbItemExchange TbItemExchange {get; private set; }

    public Tables() { }
    
    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbUIPanel_Config = new Game.TbUIPanel_Config(await loader("game_tbuipanel_config")); 
        tables.Add("Game.TbUIPanel_Config", TbUIPanel_Config);
        TbMailPanel_Config = new Game.TbMailPanel_Config(await loader("game_tbmailpanel_config")); 
        tables.Add("Game.TbMailPanel_Config", TbMailPanel_Config);
        TbZeus_Config = new Game.TbZeus_Config(await loader("game_tbzeus_config")); 
        tables.Add("Game.TbZeus_Config", TbZeus_Config);
        TbGame500_Gear = new Game.TbGame500_Gear(await loader("game_tbgame500_gear")); 
        tables.Add("Game.TbGame500_Gear", TbGame500_Gear);
        TbGame500_Line_Config = new Game.TbGame500_Line_Config(await loader("game_tbgame500_line_config")); 
        tables.Add("Game.TbGame500_Line_Config", TbGame500_Line_Config);
        TbGame600_Gear = new Game.TbGame600_Gear(await loader("game_tbgame600_gear")); 
        tables.Add("Game.TbGame600_Gear", TbGame600_Gear);
        TbGame600_JackPot = new Game.TbGame600_JackPot(await loader("game_tbgame600_jackpot")); 
        tables.Add("Game.TbGame600_JackPot", TbGame600_JackPot);
        TbGame600_Line_Config = new Game.TbGame600_Line_Config(await loader("game_tbgame600_line_config")); 
        tables.Add("Game.TbGame600_Line_Config", TbGame600_Line_Config);
        TbGame700_Base_Config = new Game.TbGame700_Base_Config(await loader("game_tbgame700_base_config")); 
        tables.Add("Game.TbGame700_Base_Config", TbGame700_Base_Config);
        TbGame700_Line_Config = new Game.TbGame700_Line_Config(await loader("game_tbgame700_line_config")); 
        tables.Add("Game.TbGame700_Line_Config", TbGame700_Line_Config);
        TbHead_Config = new Game.TbHead_Config(await loader("game_tbhead_config")); 
        tables.Add("Game.TbHead_Config", TbHead_Config);
        TbSounds_Config = new Game.TbSounds_Config(await loader("game_tbsounds_config")); 
        tables.Add("Game.TbSounds_Config", TbSounds_Config);
        TbGame800_Base_Config = new Game.TbGame800_Base_Config(await loader("game_tbgame800_base_config")); 
        tables.Add("Game.TbGame800_Base_Config", TbGame800_Base_Config);
        TbGame800_Line_Config = new Game.TbGame800_Line_Config(await loader("game_tbgame800_line_config")); 
        tables.Add("Game.TbGame800_Line_Config", TbGame800_Line_Config);
        TbGameTask = new Game.TbGameTask(await loader("game_tbgametask")); 
        tables.Add("Game.TbGameTask", TbGameTask);
        TbSevenDay_Login_Config = new Game.TbSevenDay_Login_Config(await loader("game_tbsevenday_login_config")); 
        tables.Add("Game.TbSevenDay_Login_Config", TbSevenDay_Login_Config);
        TbShop_Config = new Game.TbShop_Config(await loader("game_tbshop_config")); 
        tables.Add("Game.TbShop_Config", TbShop_Config);
        TbConst_Config = new Game.TbConst_Config(await loader("game_tbconst_config")); 
        tables.Add("Game.TbConst_Config", TbConst_Config);
        TbVip_lvl_Config = new Game.TbVip_lvl_Config(await loader("game_tbvip_lvl_config")); 
        tables.Add("Game.TbVip_lvl_Config", TbVip_lvl_Config);
        TbGameRoomConfig = new Game.TbGameRoomConfig(await loader("game_tbgameroomconfig")); 
        tables.Add("Game.TbGameRoomConfig", TbGameRoomConfig);
        TbComSysNotice_Config = new Game.TbComSysNotice_Config(await loader("game_tbcomsysnotice_config")); 
        tables.Add("Game.TbComSysNotice_Config", TbComSysNotice_Config);
        TbGame601_Gear = new Game.TbGame601_Gear(await loader("game_tbgame601_gear")); 
        tables.Add("Game.TbGame601_Gear", TbGame601_Gear);
        TbGame601_JackPot = new Game.TbGame601_JackPot(await loader("game_tbgame601_jackpot")); 
        tables.Add("Game.TbGame601_JackPot", TbGame601_JackPot);
        TbGame601_Line_Config = new Game.TbGame601_Line_Config(await loader("game_tbgame601_line_config")); 
        tables.Add("Game.TbGame601_Line_Config", TbGame601_Line_Config);
        TbSubPackConfig = new Game.TbSubPackConfig(await loader("game_tbsubpackconfig")); 
        tables.Add("Game.TbSubPackConfig", TbSubPackConfig);
        CashOut_Limit_Config = new CashOut_Limit_Config(await loader("cashout_limit_config")); 
        tables.Add("CashOut_Limit_Config", CashOut_Limit_Config);
        TbGameItemConfig = new Game.TbGameItemConfig(await loader("game_tbgameitemconfig")); 
        tables.Add("Game.TbGameItemConfig", TbGameItemConfig);
        TbGame900_Gear = new Game.TbGame900_Gear(await loader("game_tbgame900_gear")); 
        tables.Add("Game.TbGame900_Gear", TbGame900_Gear);
        TbGame900_Line_Config = new Game.TbGame900_Line_Config(await loader("game_tbgame900_line_config")); 
        tables.Add("Game.TbGame900_Line_Config", TbGame900_Line_Config);
        TbGame1000_Gear = new Game.TbGame1000_Gear(await loader("game_tbgame1000_gear")); 
        tables.Add("Game.TbGame1000_Gear", TbGame1000_Gear);
        TbGame1000_Line_Config = new Game.TbGame1000_Line_Config(await loader("game_tbgame1000_line_config")); 
        tables.Add("Game.TbGame1000_Line_Config", TbGame1000_Line_Config);
        TbGame1100_Gear = new Game.TbGame1100_Gear(await loader("game_tbgame1100_gear")); 
        tables.Add("Game.TbGame1100_Gear", TbGame1100_Gear);
        TbGame1100_Line_Config = new Game.TbGame1100_Line_Config(await loader("game_tbgame1100_line_config")); 
        tables.Add("Game.TbGame1100_Line_Config", TbGame1100_Line_Config);
        TbGameMines_Config = new Game.TbGameMines_Config(await loader("game_tbgamemines_config")); 
        tables.Add("Game.TbGameMines_Config", TbGameMines_Config);
        TbGame1200_Gear = new Game.TbGame1200_Gear(await loader("game_tbgame1200_gear")); 
        tables.Add("Game.TbGame1200_Gear", TbGame1200_Gear);
        TbGame1200_Line_Config = new Game.TbGame1200_Line_Config(await loader("game_tbgame1200_line_config")); 
        tables.Add("Game.TbGame1200_Line_Config", TbGame1200_Line_Config);
        TbGame1300_Gear = new Game.TbGame1300_Gear(await loader("game_tbgame1300_gear")); 
        tables.Add("Game.TbGame1300_Gear", TbGame1300_Gear);
        TbGame1400_BetChips = new Game.TbGame1400_BetChips(await loader("game_tbgame1400_betchips")); 
        tables.Add("Game.TbGame1400_BetChips", TbGame1400_BetChips);
        TbGame200_Config = new Game.TbGame200_Config(await loader("game_tbgame200_config")); 
        tables.Add("Game.TbGame200_Config", TbGame200_Config);
        TbShare_PayUsers_Config = new Game.TbShare_PayUsers_Config(await loader("game_tbshare_payusers_config")); 
        tables.Add("Game.TbShare_PayUsers_Config", TbShare_PayUsers_Config);
        TbShare_PromoteUsers_Config = new Game.TbShare_PromoteUsers_Config(await loader("game_tbshare_promoteusers_config")); 
        tables.Add("Game.TbShare_PromoteUsers_Config", TbShare_PromoteUsers_Config);
        TbGame1500_Gear = new Game.TbGame1500_Gear(await loader("game_tbgame1500_gear")); 
        tables.Add("Game.TbGame1500_Gear", TbGame1500_Gear);
        TbGame1500_Line_Config = new Game.TbGame1500_Line_Config(await loader("game_tbgame1500_line_config")); 
        tables.Add("Game.TbGame1500_Line_Config", TbGame1500_Line_Config);
        TbGame1000_AwardLine = new Game.TbGame1000_AwardLine(await loader("game_tbgame1000_awardline")); 
        tables.Add("Game.TbGame1000_AwardLine", TbGame1000_AwardLine);
        TbConstLevelParamVIP = new Game.TbConstLevelParamVIP(await loader("game_tbconstlevelparamvip")); 
        tables.Add("Game.TbConstLevelParamVIP", TbConstLevelParamVIP);
        TbGame1600_Gear = new Game.TbGame1600_Gear(await loader("game_tbgame1600_gear")); 
        tables.Add("Game.TbGame1600_Gear", TbGame1600_Gear);
        TbGame1600_Line_Config = new Game.TbGame1600_Line_Config(await loader("game_tbgame1600_line_config")); 
        tables.Add("Game.TbGame1600_Line_Config", TbGame1600_Line_Config);
        TbHappyGrid_Config = new Game.TbHappyGrid_Config(await loader("game_tbhappygrid_config")); 
        tables.Add("Game.TbHappyGrid_Config", TbHappyGrid_Config);
        TbGameArena = new Game.TbGameArena(await loader("game_tbgamearena")); 
        tables.Add("Game.TbGameArena", TbGameArena);
        TbGameRank = new Game.TbGameRank(await loader("game_tbgamerank")); 
        tables.Add("Game.TbGameRank", TbGameRank);
        TbGame602_Gear = new Game.TbGame602_Gear(await loader("game_tbgame602_gear")); 
        tables.Add("Game.TbGame602_Gear", TbGame602_Gear);
        TbGame602_JackPot = new Game.TbGame602_JackPot(await loader("game_tbgame602_jackpot")); 
        tables.Add("Game.TbGame602_JackPot", TbGame602_JackPot);
        TbGame602_Line_Config = new Game.TbGame602_Line_Config(await loader("game_tbgame602_line_config")); 
        tables.Add("Game.TbGame602_Line_Config", TbGame602_Line_Config);
        TbFortyTwoGrid_Config = new Game.TbFortyTwoGrid_Config(await loader("game_tbfortytwogrid_config")); 
        tables.Add("Game.TbFortyTwoGrid_Config", TbFortyTwoGrid_Config);
        TbGame700_JackPot = new Game.TbGame700_JackPot(await loader("game_tbgame700_jackpot")); 
        tables.Add("Game.TbGame700_JackPot", TbGame700_JackPot);
        TbItemExchange = new Game.TbItemExchange(await loader("game_tbitemexchange")); 
        tables.Add("Game.TbItemExchange", TbItemExchange);

        TbUIPanel_Config.Resolve(tables); 
        TbMailPanel_Config.Resolve(tables); 
        TbZeus_Config.Resolve(tables); 
        TbGame500_Gear.Resolve(tables); 
        TbGame500_Line_Config.Resolve(tables); 
        TbGame600_Gear.Resolve(tables); 
        TbGame600_JackPot.Resolve(tables); 
        TbGame600_Line_Config.Resolve(tables); 
        TbGame700_Base_Config.Resolve(tables); 
        TbGame700_Line_Config.Resolve(tables); 
        TbHead_Config.Resolve(tables); 
        TbSounds_Config.Resolve(tables); 
        TbGame800_Base_Config.Resolve(tables); 
        TbGame800_Line_Config.Resolve(tables); 
        TbGameTask.Resolve(tables); 
        TbSevenDay_Login_Config.Resolve(tables); 
        TbShop_Config.Resolve(tables); 
        TbConst_Config.Resolve(tables); 
        TbVip_lvl_Config.Resolve(tables); 
        TbGameRoomConfig.Resolve(tables); 
        TbComSysNotice_Config.Resolve(tables); 
        TbGame601_Gear.Resolve(tables); 
        TbGame601_JackPot.Resolve(tables); 
        TbGame601_Line_Config.Resolve(tables); 
        TbSubPackConfig.Resolve(tables); 
        CashOut_Limit_Config.Resolve(tables); 
        TbGameItemConfig.Resolve(tables); 
        TbGame900_Gear.Resolve(tables); 
        TbGame900_Line_Config.Resolve(tables); 
        TbGame1000_Gear.Resolve(tables); 
        TbGame1000_Line_Config.Resolve(tables); 
        TbGame1100_Gear.Resolve(tables); 
        TbGame1100_Line_Config.Resolve(tables); 
        TbGameMines_Config.Resolve(tables); 
        TbGame1200_Gear.Resolve(tables); 
        TbGame1200_Line_Config.Resolve(tables); 
        TbGame1300_Gear.Resolve(tables); 
        TbGame1400_BetChips.Resolve(tables); 
        TbGame200_Config.Resolve(tables); 
        TbShare_PayUsers_Config.Resolve(tables); 
        TbShare_PromoteUsers_Config.Resolve(tables); 
        TbGame1500_Gear.Resolve(tables); 
        TbGame1500_Line_Config.Resolve(tables); 
        TbGame1000_AwardLine.Resolve(tables); 
        TbConstLevelParamVIP.Resolve(tables); 
        TbGame1600_Gear.Resolve(tables); 
        TbGame1600_Line_Config.Resolve(tables); 
        TbHappyGrid_Config.Resolve(tables); 
        TbGameArena.Resolve(tables); 
        TbGameRank.Resolve(tables); 
        TbGame602_Gear.Resolve(tables); 
        TbGame602_JackPot.Resolve(tables); 
        TbGame602_Line_Config.Resolve(tables); 
        TbFortyTwoGrid_Config.Resolve(tables); 
        TbGame700_JackPot.Resolve(tables); 
        TbItemExchange.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbUIPanel_Config.TranslateText(translator); 
        TbMailPanel_Config.TranslateText(translator); 
        TbZeus_Config.TranslateText(translator); 
        TbGame500_Gear.TranslateText(translator); 
        TbGame500_Line_Config.TranslateText(translator); 
        TbGame600_Gear.TranslateText(translator); 
        TbGame600_JackPot.TranslateText(translator); 
        TbGame600_Line_Config.TranslateText(translator); 
        TbGame700_Base_Config.TranslateText(translator); 
        TbGame700_Line_Config.TranslateText(translator); 
        TbHead_Config.TranslateText(translator); 
        TbSounds_Config.TranslateText(translator); 
        TbGame800_Base_Config.TranslateText(translator); 
        TbGame800_Line_Config.TranslateText(translator); 
        TbGameTask.TranslateText(translator); 
        TbSevenDay_Login_Config.TranslateText(translator); 
        TbShop_Config.TranslateText(translator); 
        TbConst_Config.TranslateText(translator); 
        TbVip_lvl_Config.TranslateText(translator); 
        TbGameRoomConfig.TranslateText(translator); 
        TbComSysNotice_Config.TranslateText(translator); 
        TbGame601_Gear.TranslateText(translator); 
        TbGame601_JackPot.TranslateText(translator); 
        TbGame601_Line_Config.TranslateText(translator); 
        TbSubPackConfig.TranslateText(translator); 
        CashOut_Limit_Config.TranslateText(translator); 
        TbGameItemConfig.TranslateText(translator); 
        TbGame900_Gear.TranslateText(translator); 
        TbGame900_Line_Config.TranslateText(translator); 
        TbGame1000_Gear.TranslateText(translator); 
        TbGame1000_Line_Config.TranslateText(translator); 
        TbGame1100_Gear.TranslateText(translator); 
        TbGame1100_Line_Config.TranslateText(translator); 
        TbGameMines_Config.TranslateText(translator); 
        TbGame1200_Gear.TranslateText(translator); 
        TbGame1200_Line_Config.TranslateText(translator); 
        TbGame1300_Gear.TranslateText(translator); 
        TbGame1400_BetChips.TranslateText(translator); 
        TbGame200_Config.TranslateText(translator); 
        TbShare_PayUsers_Config.TranslateText(translator); 
        TbShare_PromoteUsers_Config.TranslateText(translator); 
        TbGame1500_Gear.TranslateText(translator); 
        TbGame1500_Line_Config.TranslateText(translator); 
        TbGame1000_AwardLine.TranslateText(translator); 
        TbConstLevelParamVIP.TranslateText(translator); 
        TbGame1600_Gear.TranslateText(translator); 
        TbGame1600_Line_Config.TranslateText(translator); 
        TbHappyGrid_Config.TranslateText(translator); 
        TbGameArena.TranslateText(translator); 
        TbGameRank.TranslateText(translator); 
        TbGame602_Gear.TranslateText(translator); 
        TbGame602_JackPot.TranslateText(translator); 
        TbGame602_Line_Config.TranslateText(translator); 
        TbFortyTwoGrid_Config.TranslateText(translator); 
        TbGame700_JackPot.TranslateText(translator); 
        TbItemExchange.TranslateText(translator); 
    }
}

}