//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Const_Config :  Bright.Config.BeanBase 
{
    public Const_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Val1 = _buf.ReadInt();
        Val2 = _buf.ReadInt();
        Val3 = _buf.ReadInt();
        Fval = _buf.ReadInt();
        Param = _buf.ReadString();
        Des = _buf.ReadString();
        PostInit();
    }

    public static Const_Config DeserializeConst_Config(ByteBuf _buf)
    {
        return new Game.Const_Config(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 常量名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 参数一
    /// </summary>
    public int Val1 { get; private set; }
    /// <summary>
    /// 参数二
    /// </summary>
    public int Val2 { get; private set; }
    /// <summary>
    /// 参数三
    /// </summary>
    public int Val3 { get; private set; }
    /// <summary>
    /// 参数四
    /// </summary>
    public int Fval { get; private set; }
    /// <summary>
    /// 字符参数
    /// </summary>
    public string Param { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Des { get; private set; }

    public const int __ID__ = 1659542586;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Val1:" + Val1 + ","
        + "Val2:" + Val2 + ","
        + "Val3:" + Val3 + ","
        + "Fval:" + Fval + ","
        + "Param:" + Param + ","
        + "Des:" + Des + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
