//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class ConstLevelParamVIP :  Bright.Config.BeanBase 
{
    public ConstLevelParamVIP(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Param1 = _buf.ReadInt();
        Param2 = _buf.ReadInt();
        Param3 = _buf.ReadInt();
        Param4 = _buf.ReadInt();
        Param5 = _buf.ReadInt();
        Param6 = _buf.ReadInt();
        PostInit();
    }

    public static ConstLevelParamVIP DeserializeConstLevelParamVIP(ByteBuf _buf)
    {
        return new Game.ConstLevelParamVIP(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 参数1
    /// </summary>
    public int Param1 { get; private set; }
    /// <summary>
    /// 参数2
    /// </summary>
    public int Param2 { get; private set; }
    /// <summary>
    /// 参数3
    /// </summary>
    public int Param3 { get; private set; }
    /// <summary>
    /// 参数4
    /// </summary>
    public int Param4 { get; private set; }
    /// <summary>
    /// 参数5
    /// </summary>
    public int Param5 { get; private set; }
    /// <summary>
    /// 参数6
    /// </summary>
    public int Param6 { get; private set; }

    public const int __ID__ = 8616141;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Param1:" + Param1 + ","
        + "Param2:" + Param2 + ","
        + "Param3:" + Param3 + ","
        + "Param4:" + Param4 + ","
        + "Param5:" + Param5 + ","
        + "Param6:" + Param6 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
