//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game1000_AwardLine :  Bright.Config.BeanBase 
{
    public Game1000_AwardLine(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Element = _buf.ReadInt();
        AwardPos = _buf.ReadString();
        Type = _buf.ReadInt();
        PostInit();
    }

    public static Game1000_AwardLine DeserializeGame1000_AwardLine(ByteBuf _buf)
    {
        return new Game.Game1000_AwardLine(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 元素ID
    /// </summary>
    public int Element { get; private set; }
    /// <summary>
    /// 中将位置
    /// </summary>
    public string AwardPos { get; private set; }
    /// <summary>
    /// 线类型
    /// </summary>
    public int Type { get; private set; }

    public const int __ID__ = -1905216545;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Element:" + Element + ","
        + "AwardPos:" + AwardPos + ","
        + "Type:" + Type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
