//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game500_Gear :  Bright.Config.BeanBase 
{
    public Game500_Gear(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        房间类型 = _buf.ReadInt();
        Gear1 = _buf.ReadInt();
        Gear2 = _buf.ReadInt();
        Gear3 = _buf.ReadInt();
        Gear4 = _buf.ReadInt();
        Gear5 = _buf.ReadInt();
        SunGold1 = _buf.ReadInt();
        SunGold2 = _buf.ReadInt();
        SunGold3 = _buf.ReadInt();
        SunGold4 = _buf.ReadInt();
        SunGold5 = _buf.ReadInt();
        SunGold6 = _buf.ReadInt();
        SunGoldRate1 = _buf.ReadInt();
        SunGoldRate2 = _buf.ReadInt();
        SunGoldRate3 = _buf.ReadInt();
        SunGoldRate4 = _buf.ReadInt();
        SunGoldRate5 = _buf.ReadInt();
        PostInit();
    }

    public static Game500_Gear DeserializeGame500_Gear(ByteBuf _buf)
    {
        return new Game.Game500_Gear(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int 房间类型 { get; private set; }
    /// <summary>
    /// 挡位1
    /// </summary>
    public int Gear1 { get; private set; }
    /// <summary>
    /// 挡位2
    /// </summary>
    public int Gear2 { get; private set; }
    /// <summary>
    /// 挡位3
    /// </summary>
    public int Gear3 { get; private set; }
    /// <summary>
    /// 挡位
    /// </summary>
    public int Gear4 { get; private set; }
    /// <summary>
    /// 挡位5
    /// </summary>
    public int Gear5 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold1 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold2 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold3 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold4 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold5 { get; private set; }
    /// <summary>
    /// 太阳币
    /// </summary>
    public int SunGold6 { get; private set; }
    /// <summary>
    /// 1挡对应的太阳币倍率
    /// </summary>
    public int SunGoldRate1 { get; private set; }
    /// <summary>
    /// 2挡对应的太阳币倍率
    /// </summary>
    public int SunGoldRate2 { get; private set; }
    /// <summary>
    /// 3挡对应的太阳币倍率
    /// </summary>
    public int SunGoldRate3 { get; private set; }
    /// <summary>
    /// 4挡对应的太阳币倍率
    /// </summary>
    public int SunGoldRate4 { get; private set; }
    /// <summary>
    /// 5挡对应的太阳币倍率
    /// </summary>
    public int SunGoldRate5 { get; private set; }

    public const int __ID__ = -451301081;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "房间类型:" + 房间类型 + ","
        + "Gear1:" + Gear1 + ","
        + "Gear2:" + Gear2 + ","
        + "Gear3:" + Gear3 + ","
        + "Gear4:" + Gear4 + ","
        + "Gear5:" + Gear5 + ","
        + "SunGold1:" + SunGold1 + ","
        + "SunGold2:" + SunGold2 + ","
        + "SunGold3:" + SunGold3 + ","
        + "SunGold4:" + SunGold4 + ","
        + "SunGold5:" + SunGold5 + ","
        + "SunGold6:" + SunGold6 + ","
        + "SunGoldRate1:" + SunGoldRate1 + ","
        + "SunGoldRate2:" + SunGoldRate2 + ","
        + "SunGoldRate3:" + SunGoldRate3 + ","
        + "SunGoldRate4:" + SunGoldRate4 + ","
        + "SunGoldRate5:" + SunGoldRate5 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
