//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameTask :  Bright.Config.BeanBase 
{
    public GameTask(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Taskid = _buf.ReadInt();
        Target = _buf.ReadLong();
        Award = _buf.ReadInt();
        Valid = _buf.ReadInt();
        PostInit();
    }

    public static GameTask DeserializeGameTask(ByteBuf _buf)
    {
        return new Game.GameTask(_buf);
    }

    /// <summary>
    /// 自增ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 任务类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 任务ID
    /// </summary>
    public int Taskid { get; private set; }
    /// <summary>
    /// 任务目标
    /// </summary>
    public long Target { get; private set; }
    /// <summary>
    /// 奖励金币
    /// </summary>
    public int Award { get; private set; }
    /// <summary>
    /// 任务是否有效
    /// </summary>
    public int Valid { get; private set; }

    public const int __ID__ = 364066579;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Taskid:" + Taskid + ","
        + "Target:" + Target + ","
        + "Award:" + Award + ","
        + "Valid:" + Valid + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
