//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameArena :  Bright.Config.BeanBase 
{
    public GameArena(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Levelid = _buf.ReadInt();
        Count = _buf.ReadInt();
        Target = _buf.ReadLong();
        Award = _buf.ReadInt();
        Title = _buf.ReadString();
        PostInit();
    }

    public static GameArena DeserializeGameArena(ByteBuf _buf)
    {
        return new Game.GameArena(_buf);
    }

    /// <summary>
    /// 自增ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 竞技场类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 竞技场等级ID
    /// </summary>
    public int Levelid { get; private set; }
    /// <summary>
    /// 名额
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// 目标
    /// </summary>
    public long Target { get; private set; }
    /// <summary>
    /// 奖励金币
    /// </summary>
    public int Award { get; private set; }
    /// <summary>
    /// 任务描述
    /// </summary>
    public string Title { get; private set; }

    public const int __ID__ = -1615891655;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Levelid:" + Levelid + ","
        + "Count:" + Count + ","
        + "Target:" + Target + ","
        + "Award:" + Award + ","
        + "Title:" + Title + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
