//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game1400_BetChips :  Bright.Config.BeanBase 
{
    public Game1400_BetChips(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        房间类型 = _buf.ReadInt();
        Chips1 = _buf.ReadInt();
        Chips2 = _buf.ReadInt();
        Chips3 = _buf.ReadInt();
        Chips4 = _buf.ReadInt();
        Chips5 = _buf.ReadInt();
        Chips6 = _buf.ReadInt();
        PostInit();
    }

    public static Game1400_BetChips DeserializeGame1400_BetChips(ByteBuf _buf)
    {
        return new Game.Game1400_BetChips(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int 房间类型 { get; private set; }
    /// <summary>
    /// 筹码1
    /// </summary>
    public int Chips1 { get; private set; }
    /// <summary>
    /// 筹码2
    /// </summary>
    public int Chips2 { get; private set; }
    /// <summary>
    /// 筹码3
    /// </summary>
    public int Chips3 { get; private set; }
    /// <summary>
    /// 筹码4
    /// </summary>
    public int Chips4 { get; private set; }
    /// <summary>
    /// 筹码5
    /// </summary>
    public int Chips5 { get; private set; }
    /// <summary>
    /// 筹码6
    /// </summary>
    public int Chips6 { get; private set; }

    public const int __ID__ = -945975452;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "房间类型:" + 房间类型 + ","
        + "Chips1:" + Chips1 + ","
        + "Chips2:" + Chips2 + ","
        + "Chips3:" + Chips3 + ","
        + "Chips4:" + Chips4 + ","
        + "Chips5:" + Chips5 + ","
        + "Chips6:" + Chips6 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
