//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game600_JackPot :  Bright.Config.BeanBase 
{
    public Game600_JackPot(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RoomType = _buf.ReadInt();
        Minor = _buf.ReadInt();
        Major = _buf.ReadInt();
        Grand = _buf.ReadInt();
        PostInit();
    }

    public static Game600_JackPot DeserializeGame600_JackPot(ByteBuf _buf)
    {
        return new Game.Game600_JackPot(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int RoomType { get; private set; }
    /// <summary>
    /// 小奖
    /// </summary>
    public int Minor { get; private set; }
    /// <summary>
    /// 中奖
    /// </summary>
    public int Major { get; private set; }
    /// <summary>
    /// 大奖
    /// </summary>
    public int Grand { get; private set; }

    public const int __ID__ = -710105569;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "RoomType:" + RoomType + ","
        + "Minor:" + Minor + ","
        + "Major:" + Major + ","
        + "Grand:" + Grand + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
