//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Game700_Base_Config :  Bright.Config.BeanBase 
{
    public Game700_Base_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RoomType = _buf.ReadInt();
        Bomb1 = _buf.ReadInt();
        Bomb2 = _buf.ReadInt();
        Bomb3 = _buf.ReadInt();
        Gear1 = _buf.ReadInt();
        Gear2 = _buf.ReadInt();
        Gear3 = _buf.ReadInt();
        Gear4 = _buf.ReadInt();
        Gear5 = _buf.ReadInt();
        Award1 = _buf.ReadString();
        Award2 = _buf.ReadString();
        Award3 = _buf.ReadString();
        PostInit();
    }

    public static Game700_Base_Config DeserializeGame700_Base_Config(ByteBuf _buf)
    {
        return new Game.Game700_Base_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间类型
    /// </summary>
    public int RoomType { get; private set; }
    /// <summary>
    /// Bomb1
    /// </summary>
    public int Bomb1 { get; private set; }
    /// <summary>
    /// Bomb2
    /// </summary>
    public int Bomb2 { get; private set; }
    /// <summary>
    /// Bomb3
    /// </summary>
    public int Bomb3 { get; private set; }
    /// <summary>
    /// 挡位1
    /// </summary>
    public int Gear1 { get; private set; }
    /// <summary>
    /// 挡位2
    /// </summary>
    public int Gear2 { get; private set; }
    /// <summary>
    /// 挡位3
    /// </summary>
    public int Gear3 { get; private set; }
    /// <summary>
    /// 挡位4
    /// </summary>
    public int Gear4 { get; private set; }
    /// <summary>
    /// 挡位5
    /// </summary>
    public int Gear5 { get; private set; }
    /// <summary>
    /// 奖励百分比
    /// </summary>
    public string Award1 { get; private set; }
    /// <summary>
    /// 奖励百分比
    /// </summary>
    public string Award2 { get; private set; }
    /// <summary>
    /// 奖励百分比
    /// </summary>
    public string Award3 { get; private set; }

    public const int __ID__ = -1700164998;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "RoomType:" + RoomType + ","
        + "Bomb1:" + Bomb1 + ","
        + "Bomb2:" + Bomb2 + ","
        + "Bomb3:" + Bomb3 + ","
        + "Gear1:" + Gear1 + ","
        + "Gear2:" + Gear2 + ","
        + "Gear3:" + Gear3 + ","
        + "Gear4:" + Gear4 + ","
        + "Gear5:" + Gear5 + ","
        + "Award1:" + Award1 + ","
        + "Award2:" + Award2 + ","
        + "Award3:" + Award3 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
