//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameRoomConfig :  Bright.Config.BeanBase 
{
    public GameRoomConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Roomid = _buf.ReadInt();
        Type = _buf.ReadInt();
        RoomNum = _buf.ReadInt();
        GameName = _buf.ReadString();
        Room1Ante = _buf.ReadFloat();
        Room2Ante = _buf.ReadFloat();
        Room3Ante = _buf.ReadFloat();
        Room1Limite = _buf.ReadFloat();
        Room2Limite = _buf.ReadFloat();
        Room3Limite = _buf.ReadFloat();
        Bannerbg = _buf.ReadString();
        TitleImg = _buf.ReadString();
        GameIcon = _buf.ReadString();
        JackPOTName = _buf.ReadString();
        Onlineid = _buf.ReadInt();
        PackName = _buf.ReadString();
        PostInit();
    }

    public static GameRoomConfig DeserializeGameRoomConfig(ByteBuf _buf)
    {
        return new Game.GameRoomConfig(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 房间顺序
    /// </summary>
    public int Roomid { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 房间数量
    /// </summary>
    public int RoomNum { get; private set; }
    /// <summary>
    /// 游戏名
    /// </summary>
    public string GameName { get; private set; }
    /// <summary>
    /// 房间1赌注
    /// </summary>
    public float Room1Ante { get; private set; }
    /// <summary>
    /// 房间2赌注
    /// </summary>
    public float Room2Ante { get; private set; }
    /// <summary>
    /// 房间3赌注
    /// </summary>
    public float Room3Ante { get; private set; }
    /// <summary>
    /// 房间1赌注限制
    /// </summary>
    public float Room1Limite { get; private set; }
    /// <summary>
    /// 房间2赌注限制
    /// </summary>
    public float Room2Limite { get; private set; }
    /// <summary>
    /// 房间3赌注限制
    /// </summary>
    public float Room3Limite { get; private set; }
    /// <summary>
    /// 大厅背景图
    /// </summary>
    public string Bannerbg { get; private set; }
    /// <summary>
    /// 标题图片
    /// </summary>
    public string TitleImg { get; private set; }
    /// <summary>
    /// 游戏图标
    /// </summary>
    public string GameIcon { get; private set; }
    /// <summary>
    /// 按钮上方文字图片
    /// </summary>
    public string JackPOTName { get; private set; }
    public int Onlineid { get; private set; }
    /// <summary>
    /// 分包名
    /// </summary>
    public string PackName { get; private set; }

    public const int __ID__ = -1654931701;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Roomid:" + Roomid + ","
        + "Type:" + Type + ","
        + "RoomNum:" + RoomNum + ","
        + "GameName:" + GameName + ","
        + "Room1Ante:" + Room1Ante + ","
        + "Room2Ante:" + Room2Ante + ","
        + "Room3Ante:" + Room3Ante + ","
        + "Room1Limite:" + Room1Limite + ","
        + "Room2Limite:" + Room2Limite + ","
        + "Room3Limite:" + Room3Limite + ","
        + "Bannerbg:" + Bannerbg + ","
        + "TitleImg:" + TitleImg + ","
        + "GameIcon:" + GameIcon + ","
        + "JackPOTName:" + JackPOTName + ","
        + "Onlineid:" + Onlineid + ","
        + "PackName:" + PackName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
