//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameRank :  Bright.Config.BeanBase 
{
    public GameRank(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Rankid = _buf.ReadInt();
        Award = _buf.ReadInt();
        Title = _buf.ReadString();
        PostInit();
    }

    public static GameRank DeserializeGameRank(ByteBuf _buf)
    {
        return new Game.GameRank(_buf);
    }

    /// <summary>
    /// 自增ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 排行类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 名次ID
    /// </summary>
    public int Rankid { get; private set; }
    /// <summary>
    /// 奖励金币
    /// </summary>
    public int Award { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Title { get; private set; }

    public const int __ID__ = 364006842;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Rankid:" + Rankid + ","
        + "Award:" + Award + ","
        + "Title:" + Title + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
