//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameItemConfig :  Bright.Config.BeanBase 
{
    public GameItemConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadString();
        PrefabName = _buf.ReadString();
        IsSmall = _buf.ReadInt();
        GameName = _buf.ReadString();
        RoomID = _buf.ReadString();
        BannerBg = _buf.ReadString();
        PeopleNumPos = _buf.ReadString();
        PostInit();
    }

    public static GameItemConfig DeserializeGameItemConfig(ByteBuf _buf)
    {
        return new Game.GameItemConfig(_buf);
    }

    /// <summary>
    /// 游戏id
    /// </summary>
    public string ID { get; private set; }
    /// <summary>
    /// 预制体名
    /// </summary>
    public string PrefabName { get; private set; }
    /// <summary>
    /// 大/小 banner
    /// </summary>
    public int IsSmall { get; private set; }
    /// <summary>
    /// 游戏名
    /// </summary>
    public string GameName { get; private set; }
    /// <summary>
    /// 房间id
    /// </summary>
    public string RoomID { get; private set; }
    /// <summary>
    /// 图片背景名
    /// </summary>
    public string BannerBg { get; private set; }
    /// <summary>
    /// 人数位置
    /// </summary>
    public string PeopleNumPos { get; private set; }

    public const int __ID__ = -581882045;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "PrefabName:" + PrefabName + ","
        + "IsSmall:" + IsSmall + ","
        + "GameName:" + GameName + ","
        + "RoomID:" + RoomID + ","
        + "BannerBg:" + BannerBg + ","
        + "PeopleNumPos:" + PeopleNumPos + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
