//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class GameMines_Config :  Bright.Config.BeanBase 
{
    public GameMines_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Grid = _buf.ReadInt();
        Type = _buf.ReadInt();
        Gear = _buf.ReadInt();
        Amount = _buf.ReadInt();
        PostInit();
    }

    public static GameMines_Config DeserializeGameMines_Config(ByteBuf _buf)
    {
        return new Game.GameMines_Config(_buf);
    }

    /// <summary>
    /// 自增ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 格子id
    /// </summary>
    public int Grid { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 挡位
    /// </summary>
    public int Gear { get; private set; }
    /// <summary>
    /// 金额
    /// </summary>
    public int Amount { get; private set; }

    public const int __ID__ = 1578912143;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Grid:" + Grid + ","
        + "Type:" + Type + ","
        + "Gear:" + Gear + ","
        + "Amount:" + Amount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
