//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class MailPanel_Config :  Bright.Config.BeanBase 
{
    public MailPanel_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Title = _buf.ReadString();
        Content = _buf.ReadString();
        PostInit();
    }

    public static MailPanel_Config DeserializeMailPanel_Config(ByteBuf _buf)
    {
        return new Game.MailPanel_Config(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 邮件标题
    /// </summary>
    public string Title { get; private set; }
    /// <summary>
    /// 邮件内容
    /// </summary>
    public string Content { get; private set; }

    public const int __ID__ = 1047307216;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Title:" + Title + ","
        + "Content:" + Content + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
