//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class SevenDay_Login_Config :  Bright.Config.BeanBase 
{
    public SevenDay_Login_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Day = _buf.ReadInt();
        Val1 = _buf.ReadInt();
        Des = _buf.ReadString();
        PostInit();
    }

    public static SevenDay_Login_Config DeserializeSevenDay_Login_Config(ByteBuf _buf)
    {
        return new Game.SevenDay_Login_Config(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 登录天数
    /// </summary>
    public int Day { get; private set; }
    /// <summary>
    /// 奖励数量(元放大一万倍)
    /// </summary>
    public int Val1 { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Des { get; private set; }

    public const int __ID__ = -1123277300;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Day:" + Day + ","
        + "Val1:" + Val1 + ","
        + "Des:" + Des + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
