//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Shop_Config :  Bright.Config.BeanBase 
{
    public Shop_Config(ByteBuf _buf) 
    {
        BuyId = _buf.ReadInt();
        Id = _buf.ReadInt();
        BuyOld = _buf.ReadInt();
        BuyNew = _buf.ReadInt();
        Diamond = _buf.ReadInt();
        GiveDiamond = _buf.ReadInt();
        BuyType = _buf.ReadInt();
        CatExp = _buf.ReadInt();
        CommodityName = _buf.ReadString();
        VipExp = _buf.ReadInt();
        NeedViplev = _buf.ReadInt();
        VipgoodsFlag = _buf.ReadInt();
        Description = _buf.ReadString();
        Iosshopid = _buf.ReadString();
        GiveDiamondtype = _buf.ReadInt();
        Img = _buf.ReadString();
        WxDescription = _buf.ReadString();
        DayGiveGold = _buf.ReadLong();
        DayGiveDiamond = _buf.ReadLong();
        PostInit();
    }

    public static Shop_Config DeserializeShop_Config(ByteBuf _buf)
    {
        return new Game.Shop_Config(_buf);
    }

    /// <summary>
    /// 商品id(100到900之间)
    /// </summary>
    public int BuyId { get; private set; }
    /// <summary>
    /// 排序id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 原价购买所需金额(分)
    /// </summary>
    public int BuyOld { get; private set; }
    /// <summary>
    /// 实际购买所需金额(分)
    /// </summary>
    public int BuyNew { get; private set; }
    /// <summary>
    /// 实际到账金额优惠后(分)
    /// </summary>
    public int Diamond { get; private set; }
    /// <summary>
    /// 额外奖励
    /// </summary>
    public int GiveDiamond { get; private set; }
    /// <summary>
    /// 购买类型
    /// </summary>
    public int BuyType { get; private set; }
    /// <summary>
    /// 获得招财猫经验(分)
    /// </summary>
    public int CatExp { get; private set; }
    /// <summary>
    /// 额外赠送百分比值
    /// </summary>
    public string CommodityName { get; private set; }
    /// <summary>
    /// 奖励Vip经验(分)
    /// </summary>
    public int VipExp { get; private set; }
    /// <summary>
    /// 购买所需要vip等级
    /// </summary>
    public int NeedViplev { get; private set; }
    /// <summary>
    /// vip商品标识
    /// </summary>
    public int VipgoodsFlag { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Description { get; private set; }
    /// <summary>
    /// 商品id(忽略)
    /// </summary>
    public string Iosshopid { get; private set; }
    /// <summary>
    /// (忽略)
    /// </summary>
    public int GiveDiamondtype { get; private set; }
    public string Img { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string WxDescription { get; private set; }
    /// <summary>
    /// 月卡每日赠送金币
    /// </summary>
    public long DayGiveGold { get; private set; }
    /// <summary>
    /// 月卡每日赠送钻石
    /// </summary>
    public long DayGiveDiamond { get; private set; }

    public const int __ID__ = -1662778161;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuyId:" + BuyId + ","
        + "Id:" + Id + ","
        + "BuyOld:" + BuyOld + ","
        + "BuyNew:" + BuyNew + ","
        + "Diamond:" + Diamond + ","
        + "GiveDiamond:" + GiveDiamond + ","
        + "BuyType:" + BuyType + ","
        + "CatExp:" + CatExp + ","
        + "CommodityName:" + CommodityName + ","
        + "VipExp:" + VipExp + ","
        + "NeedViplev:" + NeedViplev + ","
        + "VipgoodsFlag:" + VipgoodsFlag + ","
        + "Description:" + Description + ","
        + "Iosshopid:" + Iosshopid + ","
        + "GiveDiamondtype:" + GiveDiamondtype + ","
        + "Img:" + Img + ","
        + "WxDescription:" + WxDescription + ","
        + "DayGiveGold:" + DayGiveGold + ","
        + "DayGiveDiamond:" + DayGiveDiamond + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
