//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Vip_lvl_Config :  Bright.Config.BeanBase 
{
    public Vip_lvl_Config(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        NextLv = _buf.ReadInt();
        NeedExp = _buf.ReadInt();
        VipLvl = _buf.ReadString();
        ProgressProve = _buf.ReadString();
        Privilege1 = _buf.ReadString();
        Privilege2 = _buf.ReadString();
        Privilege3 = _buf.ReadString();
        Privilege4 = _buf.ReadString();
        Privilege5 = _buf.ReadString();
        Privilege6 = _buf.ReadString();
        PostInit();
    }

    public static Vip_lvl_Config DeserializeVip_lvl_Config(ByteBuf _buf)
    {
        return new Game.Vip_lvl_Config(_buf);
    }

    /// <summary>
    /// 排行区间
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 下一等级
    /// </summary>
    public int NextLv { get; private set; }
    /// <summary>
    /// 升级需求经验(分)
    /// </summary>
    public int NeedExp { get; private set; }
    /// <summary>
    /// VIP等级
    /// </summary>
    public string VipLvl { get; private set; }
    /// <summary>
    /// 进度条下文字
    /// </summary>
    public string ProgressProve { get; private set; }
    /// <summary>
    /// 特权文字1
    /// </summary>
    public string Privilege1 { get; private set; }
    /// <summary>
    /// 特权文字2
    /// </summary>
    public string Privilege2 { get; private set; }
    /// <summary>
    /// 特权文字3
    /// </summary>
    public string Privilege3 { get; private set; }
    /// <summary>
    /// 特权文字4
    /// </summary>
    public string Privilege4 { get; private set; }
    /// <summary>
    /// 特权文字5
    /// </summary>
    public string Privilege5 { get; private set; }
    /// <summary>
    /// 特权文字6
    /// </summary>
    public string Privilege6 { get; private set; }

    public const int __ID__ = -1471855363;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NextLv:" + NextLv + ","
        + "NeedExp:" + NeedExp + ","
        + "VipLvl:" + VipLvl + ","
        + "ProgressProve:" + ProgressProve + ","
        + "Privilege1:" + Privilege1 + ","
        + "Privilege2:" + Privilege2 + ","
        + "Privilege3:" + Privilege3 + ","
        + "Privilege4:" + Privilege4 + ","
        + "Privilege5:" + Privilege5 + ","
        + "Privilege6:" + Privilege6 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
