//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Game
{

public sealed partial class Zeus_Config :  Bright.Config.BeanBase 
{
    public Zeus_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Pic = _buf.ReadString();
        Type = _buf.ReadInt();
        Beishu = _buf.ReadInt();
        Multiple = _buf.ReadFloat();
        Interval = _buf.ReadString();
        PostInit();
    }

    public static Zeus_Config DeserializeZeus_Config(ByteBuf _buf)
    {
        return new Game.Zeus_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 对应图片名
    /// </summary>
    public string Pic { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 倍数显示
    /// </summary>
    public int Beishu { get; private set; }
    /// <summary>
    /// 倍数系数
    /// </summary>
    public float Multiple { get; private set; }
    /// <summary>
    /// 区间
    /// </summary>
    public string Interval { get; private set; }

    public const int __ID__ = -2088323748;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Pic:" + Pic + ","
        + "Type:" + Type + ","
        + "Beishu:" + Beishu + ","
        + "Multiple:" + Multiple + ","
        + "Interval:" + Interval + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
