/********************************************************************
作    者:	自动生成
描    述:
*********************************************************************/
namespace SEZSJ
{
	public static class NetHandlerRegister
	{
		public static void Init()
		{
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME15_BET_RET,HotUpdate.FortyTwoGridCtrl.Instance.GameBetRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME15_BROADCAST_JACKPOT,HotUpdate.FortyTwoGridCtrl.Instance.BroadCastRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME15_BROADCAST_ADD_AWARD,HotUpdate.FortyTwoGridCtrl.Instance.BroadCastAddRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME15_ROOM_INFO,HotUpdate.FortyTwoGridCtrl.Instance.RoomInfoRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME11_ROOM_INFO,HotUpdate.Game1000Ctrl.Instance.OnEnterRoomRet_1000);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME11_BET_RET,HotUpdate.Game1000Ctrl.Instance.OnGAME11_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME11_BROADCAST_ADD_AWARD,HotUpdate.Game1000Ctrl.Instance.GAME11_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME7_ROOM_INFO,HotUpdate.Game1100Ctrl.Instance.OnEnterRoomRet_1100);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME7_BET_RET,HotUpdate.Game1100Ctrl.Instance.OnGAME7_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME7_BROADCAST_ADD_AWARD,HotUpdate.Game1100Ctrl.Instance.GAME7_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME10_ROOM_INFO,HotUpdate.Game1200Ctrl.Instance.OnEnterRoomRet_1200);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME10_BET_RET,HotUpdate.Game1200Ctrl.Instance.OnGAME10_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME9_BET_RET,HotUpdate.Game1300Ctrl.Instance.OnGAME8_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_ROOM_INFO,HotUpdate.Game1400Ctrl.Instance.OnGAME12_ROOM_INFO);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BET_RET,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BROADCAST_BET,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BROADCAST_BET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BROADCAST_ADD_PLAYER,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BROADCAST_ADD_PLAYER);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BROADCAST_DEL_PLAYER,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BROADCAST_DEL_PLAYER);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BROADCAST_BET_START,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BROADCAST_BET_START);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_BROADCAST_BET_END,HotUpdate.Game1400Ctrl.Instance.OnGAME12_BROADCAST_BET_END);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME12_CALCULATE,HotUpdate.Game1400Ctrl.Instance.OnGAME12_CALCULATE);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME13_ROOM_INFO,HotUpdate.Game1500Ctrl.Instance.OnEnterRoomRet_1500);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME13_BET_RET,HotUpdate.Game1500Ctrl.Instance.OnGAME10_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME14_ROOM_INFO,HotUpdate.Game1600Ctrl.Instance.OnEnterRoomRet_1600);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME14_BET_RET,HotUpdate.Game1600Ctrl.Instance.OnGAME14_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME1_ROOM_INFO,HotUpdate.Game500Ctrl.Instance.OnEnterRoomRet_600);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME1_BET_RET,HotUpdate.Game500Ctrl.Instance.GameBetRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME1_BROADCAST_JACKPOT,HotUpdate.Game500Ctrl.Instance.GAME1_BROADCAST_JACKPOT);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME1_BROADCAST_ADD_AWARD,HotUpdate.Game500Ctrl.Instance.GAME1_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME6_ROOM_INFO,HotUpdate.Game601Ctrl.Instance.OnEnterRoomRet_601);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME6_BET_RET,HotUpdate.Game601Ctrl.Instance.OnGAME2_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME6_BROADCAST_JACKPOT,HotUpdate.Game601Ctrl.Instance.GAME6_BROADCAST_JACKPOT);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME6_BROADCAST_ADD_AWARD,HotUpdate.Game601Ctrl.Instance.GAME6_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME19_ROOM_INFO,HotUpdate.Game602Ctrl.Instance.OnEnterRoomRet_602);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME19_BET_RET,HotUpdate.Game602Ctrl.Instance.OnGAME19_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME19_BROADCAST_JACKPOT,HotUpdate.Game602Ctrl.Instance.GAME19_BROADCAST_JACKPOT);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME19_BROADCAST_ADD_AWARD,HotUpdate.Game602Ctrl.Instance.GAME19_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME2_ROOM_INFO,HotUpdate.Game700Ctrl.Instance.OnEnterRoomRet_600);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME2_BET_RET,HotUpdate.Game700Ctrl.Instance.OnGAME3_BET_RE_700);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME2_BROADCAST_JACKPOT,HotUpdate.Game700Ctrl.Instance.GAME1_BROADCAST_JACKPOT);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME2_BROADCAST_ADD_AWARD,HotUpdate.Game700Ctrl.Instance.GAME2_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME5_ROOM_INFO,HotUpdate.Game800Ctrl.Instance.OnEnterRoomRet_800);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME5_BET_RET,HotUpdate.Game800Ctrl.Instance.OnGAME3_BET_RE_800);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME5_BROADCAST_JACKPOT,HotUpdate.Game800Ctrl.Instance.OnBROADCAST_JACKPOT);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME5_BROADCAST_ADD_AWARD,HotUpdate.Game800Ctrl.Instance.OnBROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME8_ROOM_INFO,HotUpdate.Game900Ctrl.Instance.OnEnterRoomRet_900);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME8_BET_RET,HotUpdate.Game900Ctrl.Instance.OnGAME8_BET_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME8_BROADCAST_ADD_AWARD,HotUpdate.Game900Ctrl.Instance.GAME8_BROADCAST_ADD_AWARD);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_SEND_GOLD_RET,HotUpdate.GiveCtrl.Instance.OnRegisterGoldRet);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_SEND_GOLD_NOTE,HotUpdate.GiveCtrl.Instance.OnRegisterGoldNote);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_SEND_GOLD_RECORD_INFO_RET,HotUpdate.GiveCtrl.Instance.OnRegisterGiveList);
			NetHandler.Instance.Register((int)NetMsgDef.S_LOGIN,HotUpdate.LoginCtrl.Instance.LoginRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.S_CREATEROLE,HotUpdate.LoginCtrl.Instance.CreateRoleRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.S_ROLEINFO,HotUpdate.LoginCtrl.Instance.RoleInfoRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.S_ENTERGAME,HotUpdate.LoginCtrl.Instance.EnterGameRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.LC_ChangePwdForAccountRet,HotUpdate.LoginCtrl.Instance.OnChangePWDResult);
			NetHandler.Instance.Register((int)NetMsgDef.LC_ChangePwdForAccountSmsgRet,HotUpdate.LoginCtrl.Instance.OnChangePWDSmsResult);
			NetHandler.Instance.Register((int)NetMsgDef.LC_RegisterAccountSmsgRet,HotUpdate.LoginCtrl.Instance.OnRegisterAccountSmsResult);
			NetHandler.Instance.Register((int)NetMsgDef.LC_RegisterAccountRet,HotUpdate.LoginCtrl.Instance.OnRegisterAccountResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_ENTER_GAME_RET,HotUpdate.MainUICtrl.Instance.EnterGameRoomRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_LEAVE_GAME_RET,HotUpdate.MainUICtrl.Instance.LevelGameRoomRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.S_NotifyMail,HotUpdate.MainUICtrl.Instance.NotifyMailRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.S_MEINFO,HotUpdate.MainUICtrl.Instance.PlayerInfoRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_SCENE_SHOW_ME_INFO_EXTEND,HotUpdate.MainUICtrl.Instance.OnRecevieAlmsData);
			NetHandler.Instance.Register((int)NetMsgDef.SC_SCENE_VARIABLE_VALUE_INFO,HotUpdate.MainUICtrl.Instance.OnRecevieVARIABLE_VALUE_INFO);
			NetHandler.Instance.Register((int)NetMsgDef.S_GetMailResult,HotUpdate.MainUICtrl.Instance.OnGetMailResult);
			NetHandler.Instance.Register((int)NetMsgDef.S_OpenMailResult,HotUpdate.MainUICtrl.Instance.OnOpenMailResult);
			NetHandler.Instance.Register((int)NetMsgDef.S_GetMailItemResult,HotUpdate.MainUICtrl.Instance.OnGetMailItemResult);
			NetHandler.Instance.Register((int)NetMsgDef.S_DelMail,HotUpdate.MainUICtrl.Instance.OnDelMailResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_BOMBBOX_GAIN_REWARD_RET,HotUpdate.MainUICtrl.Instance.SC_TASK_BOMBBOX_GAIN_REWARD_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_BOMBBOX_UPDATE_INFO,HotUpdate.MainUICtrl.Instance.SC_TASK_BOMBBOX_UPDATE_INFO);
			NetHandler.Instance.Register((int)NetMsgDef.SC_SYNPLAYER_INFO,HotUpdate.MainUICtrl.Instance.OnSynPlayerInfo);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_GAIN_REWARD_RET,HotUpdate.MainUICtrl.Instance.OnGetTaskAwardResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_LIST_INFO,HotUpdate.MainUICtrl.Instance.OnGetTaskInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_UPDATE_INFO,HotUpdate.MainUICtrl.Instance.OnUpdateTaskInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.WC_SYNCTIME,HotUpdate.MainUICtrl.Instance.OnSyncTime);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_SIGNIN_RET,HotUpdate.MainUICtrl.Instance.OnSignInResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_DIAMOND_EXCHANGE_RET,HotUpdate.MainUICtrl.Instance.SC_DIAMOND_EXCHANGE_RET);
			NetHandler.Instance.Register((int)NetMsgDef.SC_DIAMOND_EXCHANGE_INFO,HotUpdate.MainUICtrl.Instance.SC_DIAMOND_EXCHANGE_INFO);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_GETJJJ_RET,HotUpdate.MainUICtrl.Instance.OnGetJJJResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_GETZCCAT_RET,HotUpdate.MainUICtrl.Instance.OnGetZccatResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_RECHARGE_PIX_RET,HotUpdate.MainUICtrl.Instance.BuyShopItemResult);
			NetHandler.Instance.Register((int)NetMsgDef.WC_BindAccountSmsgRet,HotUpdate.MainUICtrl.Instance.OnVerificationSMSResult);
			NetHandler.Instance.Register((int)NetMsgDef.WC_BindAccountRet,HotUpdate.MainUICtrl.Instance.OnBindPhoneResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_RECHARGE_PIX_BIND_INFO_RET,HotUpdate.MainUICtrl.Instance.OnBindPixResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_CASHOUT_PIX_RET,HotUpdate.MainUICtrl.Instance.OnCashOutPixResult);
			NetHandler.Instance.Register((int)NetMsgDef.WC_Human_Real_Name_Authentication_Ret,HotUpdate.MainUICtrl.Instance.OnWC_HUMAN_REAL_NAME_AUTHENTICATION_RET);
			NetHandler.Instance.Register((int)NetMsgDef.WC_SysNotice,HotUpdate.MainUICtrl.Instance.OnSysNoticeResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_ONLINE_MESSAGE_RET,HotUpdate.MainUICtrl.Instance.OnSendMessageResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_CASHOUT_PIX_BIND_INFO_RET,HotUpdate.MainUICtrl.Instance.OnPixBindInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_SET_ICONID_RET,HotUpdate.MainUICtrl.Instance.OnChangeIconResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_SET_PLAYER_NAME_RET,HotUpdate.MainUICtrl.Instance.OnRenameResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_RECHARGE_MONEY_RET,HotUpdate.MainUICtrl.Instance.OnRechargeMoneyRet);
			NetHandler.Instance.Register((int)NetMsgDef.SC_HUMAN_RECHARGE_RECORD_NOTICE,HotUpdate.MainUICtrl.Instance.OnRechargeRecordNotice);
			NetHandler.Instance.Register((int)NetMsgDef.SC_SYN_GAME_ONLINE_INFO,HotUpdate.MainUICtrl.Instance.OnSynGameOnlienInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_CARD_EXCHANGE_GOLD_INFO,HotUpdate.MainUICtrl.Instance.OnSC_CARD_EXCHANGE_GOLD_INFO);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_COMMRANK_CURRENT_INFO,HotUpdate.RankCtrl.Instance.GetRankInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_COMMRANK_HISTORY_INFO,HotUpdate.RankCtrl.Instance.GetLastRankInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_EXPAND_INFO_RET,HotUpdate.ShareCtrl.Instance.OnSC_TASK_EXPAND_INFO_RETResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_EXPAND_EXTRACT_RET,HotUpdate.ShareCtrl.Instance.OnSC_TASK_EXPAND_EXTRACT_RETResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_COMMARENA_CURRENT_INFO,HotUpdate.TournamentCtrl.Instance.GetTournamentInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_COMMARENA_HISTORY_INFO,HotUpdate.TournamentCtrl.Instance.GetLastTournamentInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_TASK_GOLDRANK_INFO,HotUpdate.WealthCtrl.Instance.GetRankInfoResult);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME4_BET_RET,HotUpdate.ZeusCtrl.Instance.GameBetRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME4_BROADCAST_JACKPOT,HotUpdate.ZeusCtrl.Instance.BroadCastRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME4_BROADCAST_ADD_AWARD,HotUpdate.ZeusCtrl.Instance.BroadCastAddRecevied);
			NetHandler.Instance.Register((int)NetMsgDef.SC_GAME4_ROOM_INFO,HotUpdate.ZeusCtrl.Instance.RoomInfoRecevied);
		}
	}
}
